### ISSUE TITLE
关于语言的问题

### ISSUE THREAD

**Issue by ice1000** [CDFLS/CWOJ#4]
真的觉得我们应该任性地把README写成中文

**Comment by jimmy19990** [comment]
双语版怎么样 😂

**Comment by ice1000** [comment]
如何支持双语？
不过支持双语

**Comment by jimmy19990** [comment]
其实我想说的是Readme双语。。。
当然如果网站双语也很简单，专门写个translation_cn.php和translation_en.php来存语言翻译，网站源码里echo后全换成变量。

**Comment by jimmy19990** [comment]
然后语言可以通过数据库实现也可以cookie实现

**Comment by sg-first** [comment]
其实窝也是很同意写成中文的

**Comment by ice1000** [comment]
我日,用php 写readme 也是有点6

**Comment by sg-first** [comment]
什么玩意

**Comment by jimmy19990** [comment]
卧槽 可能是我表述不清吧
编辑了一下上一条评论，自己去看。
